[package]
org = "ballerinax"
name = "webhook"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../webhook-native/build/libs/webhook-native-@project.version@.jar"
groupId = "io.ballerinax.webhook"
artifactId = "webhook-native"
version = "@project.version@"
