name: Daily build

on:
  schedule:
    - cron:  '0 */12 * * *'

jobs:
  ubuntu-build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build with Gradle
        env:
          packageUser: ${{ secrets.USER_NAME }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build

  windows-build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build with Gradle
        env:
          packageUser: ${{ secrets.USER_NAME }}
          packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
          JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
        run: ./gradlew.bat build
